# Generated by Django 2.1.3 on 2018-11-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='banner_image',
            field=models.ImageField(default=None, upload_to='challenges/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
