# Generated by Django 2.1.3 on 2018-11-04 20:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_cms', '0002_auto_20181104_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='deliverables',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activities_and_interest',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_team_clubs',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
