# Generated by Django 2.1.3 on 2018-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_cms', '0003_auto_20181104_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
