# Generated by Django 2.1.3 on 2018-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_cms', '0004_skill_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='due_date',
            field=models.DateField(),
        ),
    ]
